/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({});


Ext.application({
  controllers: [
    'VegaUi.controller.VegaRouter',
  ],
  views: [
    'MainView'
  ],
  name: 'VegaUi',

  requires: [
    // This will automatically load all classes in the VegaUi namespace
    // so that application classes do not need to require each other.
    'VegaUi.*',
  ],

  stores: [
    'Questionnaires',
    'QuestionnaireGroups',
    'QuestionnaireProfiles',
    'QuestionnaireTypes',
    'QuestEditorStore',
    'QeReplyTypes',
    'QeCheckBoxes',
    'QeReplies',
    'QeQuestions',
    'QeJeReplies',
    'CompanyRoles',
    'CompanyGroups',
    'Assessments',
    'Companies'
  ],


  launch: function () {
    Ext.ariaWarn = Ext.emptyFn
    // TODO - Launch the application, preceduto da logout
    console.log('launching')
    Ext.create('VegaUi.view.MainView');
  }

});
